package opencpn:portable@0.2.0;

interface event-subscriptions {
  use types.{service-error, subscription};

  subscribe: func(request: subscription) -> result<u64, service-error>;
  unsubscribe: func(subscription-id: u64) -> result<_, service-error>;
}

interface event-sink {
  use types.{event, service-error};

  on-event: func(value: event) -> result<_, service-error>;
}
