package opencpn:portable@0.2.0;

interface lifecycle {
  use types.{service-error};

  record plugin-info {
    id: string,
    name: string,
    version: string,
  }

  initialize: func() -> result<plugin-info, service-error>;
  enable: func() -> result<_, service-error>;
  disable: func();
  on-action: func(action-id: string) -> result<_, service-error>;
}
