package opencpn:portable@0.2.0;

interface plugin-messages {
  use types.{service-error};

  send: func(message-id: string, message-body: string)
    -> result<_, service-error>;
}

interface plugin-message-sink {
  use types.{service-error};

  on-plugin-message: func(message-id: string, message-body: string)
    -> result<_, service-error>;
}
